//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Misa.CukCukMaterial.CTM.Common.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceVN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceVN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Misa.CukCukMaterial.CTM.Common.Resource.ResourceVN", typeof(ResourceVN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string Contain {
            get {
                return ResourceManager.GetString("Contain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e011.
        /// </summary>
        public static string ConversionUnit_And_Unit_NotSame {
            get {
                return ResourceManager.GetString("ConversionUnit_And_Unit_NotSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e013.
        /// </summary>
        public static string ConversionUnit_NotEmpty {
            get {
                return ResourceManager.GetString("ConversionUnit_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string EndWith {
            get {
                return ResourceManager.GetString("EndWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =.
        /// </summary>
        public static string Equal {
            get {
                return ResourceManager.GetString("Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e002.
        /// </summary>
        public static string MaterialCode_Duplicate {
            get {
                return ResourceManager.GetString("MaterialCode_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e003.
        /// </summary>
        public static string MaterialCode_NotEmpty {
            get {
                return ResourceManager.GetString("MaterialCode_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e004.
        /// </summary>
        public static string MaterialName_NotEmpty {
            get {
                return ResourceManager.GetString("MaterialName_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !.
        /// </summary>
        public static string NotContain {
            get {
                return ResourceManager.GetString("NotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_material_GetNewCode.
        /// </summary>
        public static string Proc_GetAuto_MaterialCode {
            get {
                return ResourceManager.GetString("Proc_GetAuto_MaterialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_material_GetByID.
        /// </summary>
        public static string Proc_material_GetByID {
            get {
                return ResourceManager.GetString("Proc_material_GetByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_material_GetPaging.
        /// </summary>
        public static string Proc_material_GetPaging {
            get {
                return ResourceManager.GetString("Proc_material_GetPaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_material_InsertOne.
        /// </summary>
        public static string Proc_material_InsertOne {
            get {
                return ResourceManager.GetString("Proc_material_InsertOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_material_UpdateOne.
        /// </summary>
        public static string Proc_material_UpdateOne {
            get {
                return ResourceManager.GetString("Proc_material_UpdateOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_unit_CheckDuplicateName.
        /// </summary>
        public static string Proc_unit_CheckDuplicateName {
            get {
                return ResourceManager.GetString("Proc_unit_CheckDuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_CheckDuplicateCode.
        /// </summary>
        public static string Procedure_CheckDuplicateCode {
            get {
                return ResourceManager.GetString("Procedure_CheckDuplicateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_DeleteOne.
        /// </summary>
        public static string Procedure_DeleteOne {
            get {
                return ResourceManager.GetString("Procedure_DeleteOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_GetAll.
        /// </summary>
        public static string Procedure_GetAll {
            get {
                return ResourceManager.GetString("Procedure_GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_GetByID.
        /// </summary>
        public static string Procedure_GetByID {
            get {
                return ResourceManager.GetString("Procedure_GetByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_InsertOne.
        /// </summary>
        public static string Procedure_InsertOne {
            get {
                return ResourceManager.GetString("Procedure_InsertOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_UpdateOne.
        /// </summary>
        public static string Procedure_UpdateOne {
            get {
                return ResourceManager.GetString("Procedure_UpdateOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        public static string StartWith {
            get {
                return ResourceManager.GetString("StartWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e005.
        /// </summary>
        public static string StockCode_Duplicate {
            get {
                return ResourceManager.GetString("StockCode_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e006.
        /// </summary>
        public static string StockCode_NotEmpty {
            get {
                return ResourceManager.GetString("StockCode_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e007.
        /// </summary>
        public static string StockName_NotEmpty {
            get {
                return ResourceManager.GetString("StockName_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e010.
        /// </summary>
        public static string UnitID_NotEmpty {
            get {
                return ResourceManager.GetString("UnitID_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e008.
        /// </summary>
        public static string UnitName_Duplicate {
            get {
                return ResourceManager.GetString("UnitName_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e009.
        /// </summary>
        public static string UnitName_NotEmpty {
            get {
                return ResourceManager.GetString("UnitName_NotEmpty", resourceCulture);
            }
        }
    }
}
